#!/usr/bin/lua 

local juci = require("juci.core");

local function upnp_list_open_ports()
	local result = { ports = {} };
	local stdout = juci.shell("iptables --line-numbers -t nat -xnvL MINIUPNPD | tail -n +3");
	for line in stdout:gmatch("[^\r\n]+") do
		local num,pkts,bytes,target,proto,opt,_,_,src,dst,_,src_port,dst_port = line:match("^(%S+)%s+(%S+)%s+(%S+)%s+(%S+)%s+(%S+)%s+(%S+)%s+(%S+)%s+(%S+)%s+(%S+)%s+(%S+)%s+(%S+)%s+dpt:(%S+)%s+to:(%S+)");
		table.insert(result.ports, {
			num = num,
			packets = pkts,
			bytes = bytes,
			target = target,
			proto = proto,
			opt = opt,
			src = src_port,
			dst = dst_port
		});
	end
	print(json.encode(result))
end

juci.ubus({
	ports = upnp_list_open_ports
}, arg);
