#!/usr/bin/lua

-- Author: Reidar Cederqvist <reidar.cederqvist@gmail.com>

local juci = require("juci/core");
local json = require("juci/json");

function speedtest_run(msg)
	local testmode, packagesize, address, port = msg.testmode, msg.packagesize, msg.address, msg.port;
	local status = 0;
	local label = "success";
	local up, down;
	if (not packagesize or not address or not port) then
		print(json.encode({message = "no empty values pleace"}));
		return; 
	end;
	if(type(packagesize) ~= "number")then 
		print(json.encode({message = "packagesize must be a number"}));
		return; 
	end;
	if not testmode == "up" and not testmode == "down" and not testmode == "up_down" then
		print(json.encode({message = "allowed testmodes are: up, down and up_down"}));
		return;
	end
	if address:match("\\") or port:match("\\") then 
		print(json.encode({message = "no backspace allowed"}));
		return;
	end
	print(json.encode({message = "success"}));
	if testmode == "up" then 
		local string = "-n 1 -m tcp-send 60 "..packagesize.." -v 2 "..address.." "..port.."";
		os.execute("/usr/bin/tptest-run \""..string.."\" \"done\" &");
	elseif testmode == "down" then 
		local string = "-n 1 -m tcp-receive 60 "..packagesize.." -v 2 "..address.." "..port.."";
		os.execute("/usr/bin/tptest-run \"done\" \""..string.."\" &");
	elseif testmode == "up_down" then 
		local string1 = "-n 1 -m tcp-send 60 "..packagesize.." -v 2 "..address.." "..port.."";
		local string2 = "-n 1 -m tcp-receive 60 "..packagesize.." -v 2 "..address.." "..port.."";
		os.execute("/usr/bin/tptest-run \""..string1.."\" \""..string2.."\" &");
	end
end

juci.ubus({
	["run"] = speedtest_run
}, arg);
