#!/bin/sh

. /usr/share/libubox/jshn.sh

local SUCCESS=0

local args="$1"
local sent="none"
local received="none"
local label="success"

json_load "$args"
json_get_var testmode testmode "up_down"
json_get_var packetsize packetsize 50000
json_get_var address address
json_get_var port port

case "$testmode" in
	*up*) sent=$(tptest -n 1 -m tcp-send 60 $packetsize -v 2 $address $port | awk '/Throughput/{print($2)}') ;;
esac

case "$testmode" in
	*down*) received=$(tptest -n 1 -m tcp-receive 60 $packetsize -v 2 $address $port | awk '/Throughput/{print($2)}') ;;
esac

if [ -z "$received" -o -z "$sent" ]; then
	SUCCESS=-1;
	label="wrong address:port combination";
fi

ubus send juci.utils.speedtest "{\"status\":$SUCCESS, \"upstream\":\"$sent\",\"downstream\":\"$received\",\"label\":\"$label\"}"

