#!/bin/sh

set -e

if [ -n "$1" ]; then
	WWW="$1"
elif [ -d /www ]; then
	WWW="/www"
elif [ -d /var/www ]; then
	WWW="/var/www"
else
	exit 1
fi

for file in `find ${WWW} -type f | grep -v "\.gz" | grep -v cgi-bin`; do
	gzip -f ${file}
done
